version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
  # Application ############################################
  app:
    build: .
    container_name: micro-videos-app
    entrypoint: dockerize -template ./.docker/app/.env:.env -template ./.docker/app/.env.testing:.env.testing -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - _DB_HOST=db
      - _DB_DATABASE=code_micro_videos
      - _DB_DATABASE_TEST=code_micro_videos_test
      - _DB_USERNAME=root
      - _DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  # NGINX Server ############################################
  nginx:
    build:
      context: .docker/nginx
    container_name: micro-videos-nginx
    restart: always
    tty: true
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - app

  # Database ###################################################
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: micro-videos-db
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Redis #################################################
  redis:
    image: redis:alpine
    container_name: micro-videos-redis
    expose:
      - 6379
    networks:
      - app-network
